src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java, src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java, src/main/java/com/project/likelion13th_team1/domain/routine/dto/RoutineDto.java, src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java, src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java, src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java, src/main/java/com/project/likelion13th_team1/domain/routine/exception/RoutineErrorCode.java, src/main/java/com/project/likelion13th_team1/domain/routine/exception/RoutineException.java, src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandService.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
- #8 
- 루틴 생성
- 루틴 수정
- 루틴 삭제 (soft / 스케쥴러 미구현)
- 루틴 단일 조회
- 내 루틴 조회
=> ✨ Feat/#8: 루틴 기능 구현

.github/workflows/cicd.yml, .gitignore, Dockerfile, docker-compose.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
- #32 
- application.yml local과 aws 환경 분리
- git action 설정
- redis 기반 설치
=> 💚 ci/cd/#32: git action 설정

src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java, src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
=> 🐛fix: CorsConfig 설정 변경

src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
=> 🐛fix: Cors Error Fix

src/main/java/com/project/likelion13th_team1/domain/member/controller/MemberController.java, src/main/java/com/project/likelion13th_team1/domain/member/dto/request/MemberRequestDto.java, src/main/java/com/project/likelion13th_team1/global/apiPayload/code/GeneralErrorCode.java, src/main/java/com/project/likelion13th_team1/global/apiPayload/exception/handler/GlobalExceptionHandler.java, src/main/java/com/project/likelion13th_team1/global/security/utils/PasswordPattern.java
- #7 
- 이름 : 공백 없음
- 이메일 : 이메일 형식
- 비밀번호 : 문자, 숫자, 기호
- 그 밖의 형식 오류 추가
=> Feat/#7-4: 멤버 유효성

src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
=> 🐛fix: 토큰 재발급이 allowUrl에 포함되지 않았던 오류

src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
=> 🚀chore: CorsConfig에 PATCH 추가

src/main/java/com/project/likelion13th_team1/domain/feature/converter/FeatureConverter.java, src/main/java/com/project/likelion13th_team1/domain/feature/dto/response/FeatureResponseDto.java
=> Feat/#49-2: 특성 응답 바디에 총점수 추가

build.gradle
=> Webflux 의존성 추가

src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java, src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java, src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryService.java, src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java, src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
- #8 
- 루틴 목록 조회와 이벤트 목록조회에 옵션 추가 (그룹기준 & 루틴 id 기준)
=> Feat/#8-6: 목록 조회 편의성 증가

src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
=> 🚀chore: uri 수정

src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandService.java, src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
=> ✨feat: 회원 가입 시 그룹 3개 자동 생성

src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java, src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandService.java, src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
=> 최초 회원가입 시 루틴 그룹 자동 생성 (Gyueon)

src/main/java/com/project/likelion13th_team1/domain/alarm/dto/response/AlarmDto.java, src/main/java/com/project/likelion13th_team1/domain/alarm/service/command/AlarmCommandService.java, src/main/java/com/project/likelion13th_team1/domain/alarm/service/command/AlarmCommandServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
=> 루틴 생성 시, 알람 자동 생성 구현

build.gradle
=> ✨feat: 메일 의존성 추가

src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
=> ✨feat:  토큰 정보 추가

src/main/java/com/project/likelion13th_team1/domain/alarm/entity/Alarm.java, src/main/java/com/project/likelion13th_team1/domain/event/entity/Event.java
=> Alarm123 main 머지

src/main/java/com/project/likelion13th_team1/domain/alarm/service/command/AlarmCommandServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/event/converter/EventConverter.java, src/main/java/com/project/likelion13th_team1/domain/event/dto/response/EventResponseDto.java, src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java, src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java, src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
=> ✨feat: 이것저것

src/main/java/com/project/likelion13th_team1/global/security/kakao/controller/KakaoLoginController.java
=> ✨feat: 카카오변경

src/main/java/com/project/likelion13th_team1/domain/alarm/controller/AlarmController.java, src/main/java/com/project/likelion13th_team1/domain/alarm/service/query/AlarmQueryService.java, src/main/java/com/project/likelion13th_team1/domain/alarm/service/query/AlarmQueryServiceImpl.java
=> Alarm111 메인 머지

src/main/resources/application-prod.yml
=> ✨feat: 콘솔 로그 안뜨게

src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java, src/main/java/com/project/likelion13th_team1/global/security/kakao/controller/KakaoLoginController.java
=> ✨feat: ㅊㅊㅊㅊ
